package com.example.network;

import java.util.HashSet;
import java.util.HashMap;

public class Router {
	private final String hostname;
	private HashSet<Router> links;
	private HashMap<String, Router> knownNodesAndGateways;
	private HashMap<Router, Route> knownRoutes;

	public Router(final String hostname) {
		this.hostname = hostname;
		this.links = new HashSet<>();
		this.knownNodesAndGateways = new HashMap<>();
		this.knownRoutes = new HashMap<>();
	}
	
	public String getHostname() {
		return this.hostname;
	}
	
	HashMap<Router, Route> getRoutes() {
		// Not exactly safe!
		return knownRoutes; 
	}
	
	public void addLink(final Router router) {
		System.err.println(hostname + " adding " + router.getHostname() + " to my list of active links");
		links.add(router);
		
		addUnknownNodesFromRoute(router, new Route(router, null));

		for (Router link : links) {
			link.updateRoutingTableFrom(this);
		}
	}
	
	void updateRoutingTableFrom(final Router router) {
		if (!links.contains(router)) {
			System.err.println(hostname + " Adding " + router.getHostname() + " to my list of active links");
			links.add(router);
		}
		
		// Update local routing table with the routes from the new link
		for (Route route : router.knownRoutes.values()) {
			addUnknownNodesFromRoute(router, new Route(router, route));
		}
		
		// Propagate routing table changes through the network
		for (Router gateway : links) {
			if (!gateway.equals(router)) {
				gateway.updateRoutingTableFrom(this);
			}
		}
	}
	
	void addUnknownNodesFromRoute(final Router gateway, final Route route) {
		if (route.nextHop == this) {
			// terminate early so as not to store routing loops.
			return;
		}

		if (!knownNodesAndGateways.keySet().contains(route.nextHop.getHostname())) {
			knownNodesAndGateways.put(route.nextHop.getHostname(), gateway);
		}

		// recur until we reach the end of the route
		if (route.route != null) {
			addUnknownNodesFromRoute(gateway, route.route);
		}
		
		knownRoutes.put(route.nextHop, route);
	}
	
	void receiveRoutingMap(Router sender, HashSet<Router> incomingLinks) {
		throw new UnsupportedOperationException("Implementation left as an exercise to the reader.");
	}

	/**
	 * Determine if the destination is routable from this Router
	 * 
	 * After checking to see if this Router is, or is directly connected to,
	 * the destination, performs a naive depth-first search for the destination
	 * 
	 * @param destination The destination router
	 * @return Whether or not the destination is routable
	 */
	public boolean canRouteTo(final String destination) {
		if (destination.equals(hostname)) {
			return true;
		}
		
		System.err.println("I have " + links.size() + " active links.");
		for (Router link : links) {
			System.err.println("Have a link to " + link.getHostname());
			if (link.getHostname().equals(destination)) {
				return true;
			}
		}
		
		return (knownNodesAndGateways.keySet().contains(destination));
		
//		for (Router link : links) {
//			if (link.canRouteTo(destination)) {
//				return true;
//			}
//		}
//		
//		return false;
	}
	
	/**
	 * Nodes with duplicate hostnames are considered to be identical
	 * 
	 * Autogenerated by Eclipse 3.8
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((hostname == null) ? 0 : hostname.hashCode());
		return result;
	}
	
	/**
	 * Nodes with duplicate hostnames are considered to be identical
	 * 
	 * Autogenerated by Eclipse 3.8
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Router other = (Router) obj;
		if (hostname == null) {
			if (other.hostname != null)
				return false;
		} else if (!hostname.equals(other.hostname))
			return false;
		return true;
	}

	private class Route {
		private final Router nextHop;
		private final Route route;
		
		Route(final Router nextHop, final Route route) {
			this.nextHop = nextHop;
			this.route = route;
		}

		/**
		 * Autogenerated by Eclipse 3.8
		 */
		@Override
		public int hashCode() {
			final int prime = 31;
			int result = 1;
			result = prime * result + getOuterType().hashCode();
			result = prime * result
					+ ((nextHop == null) ? 0 : nextHop.hashCode());
			result = prime * result + ((route == null) ? 0 : route.hashCode());
			return result;
		}

		/**
		 * Autogenerated by Eclipse 3.8
		 */
		@Override
		public boolean equals(Object obj) {
			if (this == obj)
				return true;
			if (obj == null)
				return false;
			if (getClass() != obj.getClass())
				return false;
			Route other = (Route) obj;
			if (!getOuterType().equals(other.getOuterType()))
				return false;
			if (nextHop == null) {
				if (other.nextHop != null)
					return false;
			} else if (!nextHop.equals(other.nextHop))
				return false;
			if (route == null) {
				if (other.route != null)
					return false;
			} else if (!route.equals(other.route))
				return false;
			return true;
		}

		private Router getOuterType() {
			return Router.this;
		}
		
		
	}
}
